### PR TITLE
Import data from BE output (http://bugseverywhere.org/)

### PR DESCRIPTION
**Pull request by mcepl**
No one is assigned

This is not finished yet ... somehow comments are not attached and I cannot figure out why. Any ideas why?

Attached is also example export of bugs from BE (issues.xml) for testing.

### CODE REVIEW

**Comment by mcepl** [comment]
@glogiotatidis , @duncanvr ... any thoughts how to make this working, please?

**Comment by DuncanvR** [comment]
Hi @mcepl,
I haven't used gitissius in some time now, and I've never been that familiar with the codebase to begin with. I might have a look at some stage, but I can't promise anything soon.
Cheers,
Duncan

**Comment by mcepl** [comment]
> but I can't promise anything soon.

This bug starts with “mcepl commented on 26 Sep 2013” and this is the first comment by somebody else … I don’t think I expect much here ;)

**Comment by glogiotatidis** [comment]
Unfortunately I don't have any time to work on this and I'm not using gitissius any more.

**Pull request closed without merging**
